fitness_club/fitness_club/urls.py
from django.contrib import admin
from django.urls import path, include

from manager.views import HomeView , AboutView , ContactView


urlpatterns = [
    path('', HomeView.as_view() , name='home' ),
    path('about/', AboutView.as_view() , name='about' ),
    path('contact_us/', ContactView.as_view() , name='contact' ),
    path('manager/' , include('manager.urls')),
    path('admin/', admin.site.urls),
]

fitness_club/manager/urls.py
from django.urls import path, include
from manager import views
from django.contrib.auth import views as authviews

app_name = 'manager'

urlpatterns = [
    path('', views.AdminDash.as_view(), name='adminDash'),
    path('create/', views.CreateAdmin.as_view(), name='adminC'),
    path('login/', authviews.LoginView.as_view(template_name='admin_login.html'),
         name='adminLogin'),
    path('logout/', authviews.LogoutView.as_view(), name='adminLogout'),

    path('member/search/', views.SearchMember, name='memberSearch'),
    path('member/create/', views.CreateMember.as_view(), name='memberC'),
    path('member/', views.ViewAllMembers.as_view(), name='memberlist'),
    path('member/<int:pk>', views.ViewsDetailMember.as_view(), name='memberDetail'),
    path('member/update/<int:pk>',
         views.UpdateMemberDetails.as_view(), name='memberUpdate'),
    path('member/delete/<int:pk>',
         views.DeleteMemberDetails.as_view(), name='memberDelete'),

    path('trainer/search/', views.SearchTrainer, name='trainerSearch'),
    path('trainer/create/', views.CreateTrainer.as_view(), name='trainerC'),
    path('trainer/', views.ViewAllTrainers.as_view(), name='trainerlist'),
    path('trainer/<int:pk>', views.ViewsDetailTrainer.as_view(), name='trainerDetail'),
    path('trainer/update/<int:pk>', views.UpdateTrainerDetails.as_view(),
         name='trainerUpdate'),
    path('trainer/delete/<int:pk>', views.DeleteTrainerDetails.as_view(),
         name='trainerDelete'),

     path('member/add/fee' , views.CreateFee.as_view() , name='memberFee'),
     path('member/add/fee/<int:pk>' , views.CreateFee.as_view() , name='memberFeeById'),

]

fitness_club/templates/about.html
{% extends 'base.html' %}

{% block body_block %}

<div class="container">
    <h1 class="text-center my-5 display-4 text-info  ">About Us</h1>
    
    <div class="pb-5" style="font-weight: bold;">
        <p>A gym, short for gymnasium, is an open air or covered location for gymnastics and athletics and gymnastic services such as in schools and colleges, from the ancient Greek gymnasium.</p>
    <p>Gymnasia apparatus such as bar-bells, parallel bars, jumping board, running path, tennis-balls, cricket field, fencing area, and so forth are used as exercises. In safe weather, outdoor locations are the most conductive to health. Gyms were popular in ancient Greece. Their curricula included Gymnastica militaria or self-defense, gymnastica medica, or physical therapy to help the sick and injured, and gymnastica athletica for physical fitness and sports, from boxing to dance.</p>
    <p>These gymnasia also had teachers of wisdom and philosophy. Community gymnastic events were done as part of the celebrations during various village festivals. In ancient Greece there was a phrase of contempt, "He can neither swim nor write." After a while, however, Olympic athletes began training in buildings just for them.</p>
    <p>Community sports never became as popular among ancient Romans as it had among the ancient Greeks. Gyms were used more as a preparation for military service or spectator sports. During the Roman Empire, the gymnastic art was forgotten. In the Dark Ages there were sword fighting tournaments and of chivalry; and after gunpowder was invented sword fighting began to be replaced by the sport of fencing. There were schools of dagger fighting and wrestling and boxing.</p>
    </div>
</div>


{% endblock %}

fitness_club/templates/admin_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body_block %}

<div class="container">
    <form method="POST">
        <h4>You sure you want to delete: <br> <strong>{{admin.username|upper }}</strong> ? </h4>
        <a href="#" ><input type="submit" class="btn btn-success" value="CANCEL"></a>
        <input type="submit" class="btn btn-danger" value="CONFIRM DELETE">
    </form>
</div>

{% endblock %}

fitness_club/templates/admin_dash.html
{% extends 'admin_base.html' %}
{% load staticfiles %}

    
{% block body_block %}
    
    <!-- Counts Section -->
      <section class="dashboard-counts section-padding">
        <div class="container-fluid">
          <div class="row">
            <!-- Count item widget-->
            <div class="col-md-4">
              <div class="wrapper count-title d-flex">
                <div class="icon"><i class="icon-user"></i></div>
                <div class="name"><strong class="text-uppercase">Total Members</strong>
                  <div class="count-number"> {{ member_count }} </div>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-md-4">
              <div class="wrapper count-title d-flex">
                <div class="icon"><i class="icon-padnote"></i></div>
                <div class="name"><strong class="text-uppercase">Total Trainers</strong>
                  <div class="count-number"> {{ trainer_count }}</div>
                </div>
              </div>
            </div>
            <!-- Count item widget-->
            <div class="col-md-4">
              <div class="wrapper count-title d-flex">
                <div class="icon"><i class="icon-check"></i></div>
                <div class="name"><strong class="text-uppercase"> members subscribed This month </strong>
                  <div class="count-number">{{daily_member_count}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


      <!-- Header Section-->
      <section class="dashboard-header section-padding">
        <div class="container-fluid">
          <div class="row d-flex align-items-md-stretch">

            <!-- To Do List-->
            <div class="col-lg-3 col-md-6 ">
              <div class="card to-do">
                <h2 class="display h4">Aim</h2>
                <p>A gym, short for gymnasium, is an open air or covered location for gymnastics and athletics and gymnastic services such as in schools and colleges, from the ancient Greek gymnasium.</p>
                
                <ul class="check-lists list-unstyled">
                  <li class="d-flex align-items-center"> 
                    <input type="checkbox" id="list-1" name="list-1" class="form-control-custom">
                    <label for="list-1">A admin can only add other admins.</label>
                  </li>
                  <li class="d-flex align-items-center"> 
                    <input type="checkbox" id="list-2" name="list-2" class="form-control-custom">
                    <label for="list-2">To delete, remove, update goto django admin panel</label>
                  </li>
                  <li class="d-flex align-items-center"> 
                    <input type="checkbox" id="list-3" name="list-3" class="form-control-custom">
                    <label for="list-3">admin can add,remove,update, view details of any member </label>
                  </li>
                  <li class="d-flex align-items-center"> 
                    <input type="checkbox" id="list-4" name="list-4" class="form-control-custom">
                    <label for="list-4">admin can add,remove,update, view details of any trainer</label>
                  </li>

                </ul>
              </div>
            </div>

            <!-- Pie Chart-->
            <div class="col-lg-3 col-md-6">
              <div class="card project-progress">
                <h2 class="display h4">About us</h2>
                <p> Gymnasia apparatus such as bar-bells, parallel bars, jumping board, running path, tennis-balls, cricket field, fencing area, and so forth are used as exercises.</p>
                <div class="pie-chart">
                  <canvas id="pieChart" width="300" height="300"> </canvas>
                </div>
              </div>
            </div>
            <!-- Line Chart -->
            <div class="col-lg-6 col-md-12 flex-lg-last flex-md-first align-self-baseline">
              <div class="card sales-report">
                <h2 class="display h4">Members report</h2>
                <p>we done have policy of sharing members details with anyone.</p>
                <div class="line-chart">
                  <canvas id="lineCahrt"></canvas>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>



      <!-- Statistics Section-->
      <section class="statistics ">
        <div class="container-fluid">
          <div class="row d-flex">
            <div class="col-lg-4">
              <!-- Income-->
              <a href="{% url 'manager:memberC' %}" class="">
                <div class="card income text-center bg-success text-dark">
                  <div class="number">Add New Member</div>
                </div>
              </a>
            </div>
            <div class="col-lg-4">
              <!-- Monthly Usage-->
              <a href="{% url 'manager:trainerC' %}" class="">
                <div class="card income text-center bg-success text-dark">
                  <div class="number">Add New Trainer</div>
                </div>
              </a>
            </div>

            <div class="col-lg-4">
              <!-- User Actibity-->
                <a href="{% url 'manager:adminC' %}" class="">
                  <div class="card income text-center bg-success text-dark">
                    <div class="number">Add New Admin</div>
                  </div>
                </a>
            </div>
          </div>
        </div>
      </section>

      <!-- Updates Section -->
      <section class="mt-30px mb-30px">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-4 ">
              <!-- Recent members          -->
              <div id="new-updates" class="card updates recent-updated">
                <div id="updates-header" class="card-header d-flex justify-content-between align-items-center">
                  <h2 class="h5 display"><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box">Recent Members</a></h2><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box"><i class="fa fa-angle-down"></i></a>
                </div>
                <div id="updates-box" role="tabpanel" class="collapse show">
                  <ul class="news list-unstyled">
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{m1_username  }}</strong>
                          <p>{{m1_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{m1_date}}</div>
                      </div>
                    </li>
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{m0_username  }}</strong>
                          <p>{{m0_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{m0_date}}</div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- Recent members End-->
            </div>

            <div class="col-lg-4 ">
              <!-- Recent treainer          -->
              <div id="new-updates" class="card updates recent-updated">
                <div id="updates-header" class="card-header d-flex justify-content-between align-items-center">
                  <h2 class="h5 display"><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box">Recent Trainers</a></h2><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box"><i class="fa fa-angle-down"></i></a>
                </div>
                <div id="updates-box" role="tabpanel" class="collapse show">
                  <ul class="news list-unstyled">
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{t0_username  }}</strong>
                          <p>{{t0_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{t0_date}}</div>
                      </div>
                    </li>
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{t1_username  }}</strong>
                          <p>{{t1_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{t1_date}}</div>
                      </div>
                    </li>        
                  </ul>
                </div>
              </div>
              <!-- Recent trainer End-->
            </div>

            <div class="col-lg-4 ">
              <!-- Recent members          -->
              <div id="new-updates" class="card updates recent-updated">
                <div id="updates-header" class="card-header d-flex justify-content-between align-items-center">
                  <h2 class="h5 display"><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box">Recent Members</a></h2><a data-toggle="collapse" data-parent="#new-updates" href="#updates-box" aria-expanded="true" aria-controls="updates-box"><i class="fa fa-angle-down"></i></a>
                </div>
                <div id="updates-box" role="tabpanel" class="collapse show">
                  <ul class="news list-unstyled">
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{m1_username  }}</strong>
                          <p>{{m1_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{m1_date}}</div>
                      </div>
                    </li>
                    <!-- Item-->
                    <li class="d-flex justify-content-between"> 
                      <div class="left-col d-flex">
                        <div class="icon"><i class="icon-rss-feed"></i></div>
                        <div class="title"><strong>{{m0_username  }}</strong>
                          <p>{{m0_email}}</p>
                        </div>
                      </div>
                      <div class="right-col text-right">
                        <div class="update-date">{{m0_date}}</div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- Recent members End-->
            </div>
            
          </div>
        </div>
      </section>


{% endblock %}

fitness_club/templates/admin_login.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Dashboard by Bootstrapious.com</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %} ">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="{% static 'css/grasp_mobile_progress_circle-1.0.0.min.css' %}">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body class="">

    <div class="page login-page" style="background-color:#808080;">
      <div class="container ">
        <div class="form-outer text-center d-flex align-items-center ">
          <div class="form-inner">
            <div class="logo text-uppercase"><span>Rawalpindi</span><strong class="text-primary">Fitness Club</strong></div>
            <p>Enter your email and password to login to your account</p>

            <div class="container">
              <h1>Admin login</h1>
              <form method="POST">
                  {% csrf_token %}
                  {% bootstrap_form form %}
                  <input type="submit" class="btn btn-success" value="Log In">
              </form>
            </div>
          
          </div>
          <div class="copyrights text-center">
            <p class="text-light">Developed by <a class="external "><small>piper soft</small></a></p>
            <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
          </div>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper.js/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/chart.js/Chart.min.js"></script>
    <script src="vendor/jquery-validation/jquery.validate.min.js"></script>
    <script src="vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Main File-->
  </body>
</html>

fitness_club/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Dashboard by Bootstrapious.com</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %} ">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="{% static 'css/grasp_mobile_progress_circle-1.0.0.min.css' %}">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="{% static 'vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>

    <div class="">
      <!-- navbar-->
      <header class="header">
        <nav class="navbar fixed-top">
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <div class="navbar-header"><a href="index.html" class="navbar-brand"></a>
                  <div class="brand-text d-none d-md-inline-block"><span class="text-light">Rawalpindi </span><strong class="text-primary">Fitness Club</strong></div></a></div>
              
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <li class="nav-item"><a href="{% url 'home' %}" class="nav-link logout"> <span class="d-none d-sm-inline-block">Home</span>
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link logout"> <span class="d-none d-sm-inline-block">About Us</span>
                <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link logout"> <span class="d-none d-sm-inline-block">Contact</span>

                <!-- Log out-->
                <li class="nav-item"><a href="{% url 'manager:adminLogin' %}" class="nav-link logout"> <span class="d-none d-sm-inline-block">Admin Login</span><i class="fa fa-users "></i></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <div style="background-color: #dedede;">

        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'img/one.jpg' %}" alt="fst slide">
                <div class="carousel-caption">
                  <h3 class="display-4 text-primary" style="font-weight: bolder;">RAWALPINDI FITNESS CLUB</h3>
                  <p class="display-4" style="font-weight: bold;" >Action is the foundational key to all success.</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'img/two.jpg' %}" alt="snd slide">
                <div class="carousel-caption">
                  <h3 class="display-4 text-primary" style="font-weight: bolder;">RAWALPINDI FITNESS CLUB</h3>
                  <p class="display-4" style="font-weight: bold;" >Action is the foundational key to all success.</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'img/three.jpg' %}" alt="trd slide">
                <div class="carousel-caption">
                  <h3 class="display-4 text-primary" style="font-weight: bolder;">RAWALPINDI FITNESS CLUB</h3>
                  <p class="display-4" style="font-weight: bold;" >Action is the foundational key to all success.</p>
                </div>   
              </div>
            </div>

          </div>


        {% block body_block %}



        {% endblock %}

      </div>


 
    </div>



    <!-- JavaScript files-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/popper.js/umd/popper.min.js"> </script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
</html>

fitness_club/templates/fee_form.html
{% extends 'admin_base.html' %}
{% load bootstrap4 %}
{% block body_block %}

<div  class="p-5">
    <h1>Add member fee</h1>

    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" value="Proceed">
    </form>
</div>

{% endblock %}

fitness_club/templates/home.html
{% extends 'base.html' %}

{% block body_block %}

<div class="">

    <div class="row height bg-secondary align-items-center pl-2" style="min-height: 80vh;">
        <div class="col">
            <h2 class="text-capitalize display-4">
                <strong class="text-danger">RAWALPINDI <span class="text-success">FITNESS CLUB</span></strong>
            </h2>
            <p>A gym, short for gymnasium, is an open air or covered location for gymnastics and athletics and gymnastic services such as in schools and colleges, from the ancient Greek gymnasium.
            </p>
            <p>Gymnasia apparatus such as bar-bells, parallel bars, jumping board, running path, tennis-balls, cricket field, fencing area, and so forth are used as exercises. In safe weather, outdoor locations are the most conductive to health. Gyms were popular in ancient Greece. Their curricula included Gymnastica militaria or self-defense, gymnastica medica, or physical therapy to help the sick and injured, and gymnastica athletica for physical fitness and sports, from boxing to dance.</p>
        </div>
    </div>

    <div class="py-5 text-center text-white " style="background-color: #4e20ff;">
        <h2 class="display-5 ">want to join</h2>
        <p>This is our 24/7 contact number</p>
        <button class="btn bg-warning" data-toggle="modal" data-target="#exampleModalCenter">join now</button>
    </div>


</div>







{% endblock %}

fitness_club/templates/member_detail.html
{% extends 'admin_base.html' %}
{% load bootstrap4 %}
{% block body_block %}

<div class="container">
    
    <div class="row">
      <div class="col-md-6">
          <h3 class=""><strong>username:</strong><span style="font-size: 24px;">{{member_info_detail.username}}</span></h3>
          <h3><strong>name:</strong> {{member_info_detail.name}}</h3>
          <h3><strong>email:</strong> {{member_info_detail.email}}</h3>
          <h3><strong>age:</strong> {{member_info_detail.age}}</h3>
          <h3><strong>height:</strong> {{member_info_detail.height}}</h3>
          <h3><strong>weight:</strong> {{member_info_detail.weight}}</h3>
      </div>
      <div class="col-md-6">
          <div class="mt-5">
            <a class="btn btn-primary btn-lg rounded" href="{% url 'manager:memberFeeById'  pk=member_info_detail.pk %}"> Add Fee </a>
            <a class="btn btn-primary btn-lg rounded" href="{% url 'manager:memberUpdate' pk=member_info_detail.pk %}"> Update Details </a>
            <a class="btn btn-danger btn-lg rounded" href="{% url 'manager:memberDelete' pk=member_info_detail.pk %}"> Delete Member </a>
          </div>
      </div>

    </div>


    <table class="table table-secondary">
        <thead class="thead-dark">
          <tr>
            <th scope="col">amount</th>
            <th scope="col">month</th>
            <th scope="col">date_paid</th>
          </tr>
        </thead>
        <tbody>
            {% for i in member_info_detail.fee.all %}
                <tr>
                    <td> {{i.amount}} </td>
                    <td> {{i.month}} </td>
                    <td> {{i.date_paid}} </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
 
</div>

{% endblock %}

fitness_club/templates/trainer_detail.html
{% extends 'admin_base.html' %}
{% load bootstrap4 %}
{% block body_block %}

<div class="container">

  <div class="row">
    <div class="col-mmd-6">
      <h1>Detail of  trainer : <strong>{{trainer_info_detail.username}}</strong></h1>
      <h3><strong>username:</strong> {{trainer_info_detail.username}}</h3>
      <h3><strong>name:</strong> {{trainer_info_detail.name}}</h3>
      <h3><strong>email:</strong> {{trainer_info_detail.email}}</h3>
    </div>
    <div class="col-md-6 text-center">
      <div class="mt-5">
        <a class="btn btn-primary btn-lg rounded" href="{% url 'manager:trainerUpdate' pk=trainer_info_detail.pk %}"> Update Details </a>
        <a class="btn btn-danger btn-lg rounded" href="{% url 'manager:trainerDelete' pk=trainer_info_detail.pk %}"> Delete Trainer </a>
      </div>
    </div>
  </div>

    <table class="table table-secondary">
        <thead class="thead-dark">
          <tr>
            <th scope="col">amount</th>
            <th scope="col">month</th>
            <th scope="col">date_paid</th>
          </tr>
        </thead>
        <tbody>
            <!-- {% for i in member_info_detail.fee.all %}
                <tr>
                    <td> {{i.amount}} </td>
                    <td> {{i.month}} </td>
                    <td> {{i.date_paid}} </td>
                </tr>
            {% endfor %} -->
        </tbody>
      </table>
    


</div>

{% endblock %}

fitness_club/templates/trainer_list.html
{% extends 'admin_base.html' %}
{% load bootstrap4 %}
{% block body_block %}

<div class="container">
    
    <div class="row" style="background-color: #212429;">
        <div class="col-md-6">
          <h1 class="text-light text-center py-3" >List of trainers</h1>
        </div>
        <div class="col-md-6 m-auto ">
      
          <form class="form-inline my-2 my-lg-0 pl-3" method="POST" action="{% url 'manager:trainerSearch' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="searh" placeholder="Search only by username" aria-label="Search" name='data' >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>

<table class="table table-secondary">
    <thead class="thead-dark">
          <tr>
            <th scope="col">username</th>
            <th scope="col">name</th>
            <th scope="col">email</th>
          </tr>
        </thead>
        <tbody>
        {% for i in trainer_info %}
            <tr>
                <td><a href="{% url 'manager:trainerDetail' pk=i.pk %}"> {{i.username}} </a></td>
                <td> {{i.name}} </td>
                <td> {{i.email}} </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    


</div>

{% endblock %}